name: Build .NET Framework Project with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet packages
        run: nuget restore ProjectForLanguage.sln

      - name: Build solution
        run: msbuild ProjectForLanguage.sln /p:Configuration=Release

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=EsmaKocabas_VocabularyApp
            -Dsonar.organization=EsmaKoca
