name: Build .NET Framework Project with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: MSBuild Kurulumu
        uses: microsoft/setup-msbuild@v1.1

      - name: SonarScanner for MSBuild Kurulumu
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Analizini Başlat
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN2 }}
        run: |
          dotnet sonarscanner begin /k:"esmakocabas" /o:"esmakocabas" /d:sonar.login="${{ secrets.SONAR_TOKEN2 }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: NuGet Paketlerini Yükle
        run: nuget restore ProjectForLanguage.sln

      - name: Projeyi Derle
        run: msbuild ProjectForLanguage.sln /p:Configuration=Release

      - name: SonarCloud Analizini Bitir
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN2 }}
        run: |
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN2 }}"
